###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "phoneNumber": "123",
  "password": "123"
}

###

GET http://localhost:8080/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDAyMTEwNzUsInN1YiI6IjEyMyIsImV4cCI6MTc0MDIxNDY3NX0.PS_rV_xnuZQvR2iPXy7DaP412_iNTWBBVYpU1ff3W5E

###