spring:
  profiles:
    active: prod
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
my_token:
  expire_time: 604800000
