spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  application:
    name: book-shop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: MySuperSecretKeyThatIsAtLeast32CharactersLong
  expire_time: 3600000