spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  application:
    name: book-shop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: prod

my_token:
  key: ${TOKEN_KEY}
  expire_time: 604800000
