spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

my_token:
  key: ${TOKEN_KEY}
  expire_time: ${TOKEN_EXPIRE:604800000}
