spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  application:
    name: book-shop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: MySuperSecretKeyThatIsAtLeast32CharactersLong
  expire_time: 3600000